# Config specific to this site

framework:
  assets:
    version: 'v61'

parameters:

    site_from_address: 'dev@positivemint.com'
#    site_from_address: 'contact@blueline-group.com'

    locale: en

    app.locales: en

    app.loginUrl: lopbfdsfn2398nfsdf983r
    app.adminUrl: adpbsdfhnj3984rnsdkf9d

    app.defaultFont: Lato

    app.fonts:
      Lato:
        class: lato
        weights:
          Thin: 100
          Light: 300
          Regular: 400
          Bold: 700
          Black: 900

    app.styleConstants:
      TB: 60px

    app.articleTypes:

      activity:
        fields:
          banner:
            type: image
          thumbnail:
            type: image
          title:
            type: text
          time:
            type: text
          description:
            type: text
            rows: 5
          albums:
            type: album
            selectorValue: title
            flags: [multiple]

#        date:
#          type: date
#          flags: [includeInAdmin]
#        title:
#          type: text
#          flags: [includeInAdmin]
#        subTitle:
#          type: text
#        body:
#          type: simpleHtml
#        priority:
#          type: bool
##          icon: exclamation
#        published:
#          type: bool
#          icon: tickCross

#        moreHtml:
#          type: simpleHtml

      album:
        fields:

#        date:
#          type: date
          title:
            type: text
          images:
            type: image
            flags: [multiple]

      pdf:
        fields:
          name:
            type: text
            info: This name is used to create the filename/url - so if you change it, you'll break any links you've created
            flags: [required]
          pdf:
            type: file
            mimeTypes: [application/pdf]
            flags: [useAsPageLink]
            filenameField: name

#        description:
#          type: text


# Twig Configuration
twig:
  globals:
    articleAdminPage: '/edit/activity'
    legacyFlags:
      renderPTags
    siteBlocks:
      facebook: Facebook
      albums: Photo Albums Accordion

swiftmailer:
  disable_delivery: true
#  delivery_addresses: ['contact@blueline-group.com'] This overrides to address set in code - use at your peril


liip_imagine:

  filter_sets:

    galleryThumb:

      quality: 70

      filters:

        scale:

          dim: [ 400,400 ]