# Config specific to this site

framework:
  assets:
    version: '61'

parameters:

  site_from_address: 'dev@positivemint.com'
  #    site_from_address: 'contact@blueline-group.com'

  locale: en

  app.locales: en

  app.loginUrl: lopbfdsfn2398nfsdf983r
  app.adminUrl: adpbsdfhnj3984rnsdkf9d

  app.defaultFont: Lato

  app.fonts:
    Lato:
      class: lato
      weights:
        Thin: 100
        Light: 300
        Regular: 400
        Bold: 700
        Black: 900

  app.styleConstants:
    TB: 60px

  app.articleTypes:

    #   why multilingual!!!
    page:
      flags: [ addRoutes ,multilingual, uniquePageId ]
      fields:
        name:
          type: text
          flags: [ required,fixed ]
        url:
          type: url
          flags: [ required, showInMobileAdmin ]

    activity:
      flags: [ confirmDeletion ]
      fields:
        banner:
          type: image
        thumbnail:
          type: image
          flags: [ showInMobileAdmin ]
        title:
          type: text
          flags: [ showInMobileAdmin ]
        time:
          type: text
        description:
          type: text
          rows: 5
        albums:
          type: album
          selectorValue: title
          flags: [ multiple ]

    news:
      order: [ priority, order, date ]
      flags: [ confirmDeletion ]
      fields:
        order:
          type: order
        title:
          type: text
          flags: [ showInMobileAdmin ]
        date:
          type: date
        category:
          type: option
          options: [ News,Fixtures,Results,Social,Rules ]
        mainText:
          label: Main Text
          type: simpleHtml
          rows: 10
        table:
          label: League Table
          type: table
          columns: [150,70,25,25,25,25,25,25,50,50,50,50]
          heading: [ [ '',Games,W,D,L,W,D,L,F,A,Diff,Points ] ]
        priority:
          type: bool

    album:
      order: [ order ]
      flags: [ confirmDeletion ]
      fields:
        order:
          type: order
        title:
          type: text
          flags: [ showInMobileAdmin ]
        images:
          type: image
          flags: [ multiple,ordered ]

    pdf:
      fields:
        name:
          type: text
          info: This name is used to create the filename/url - so if you change it, you'll break any links you've created
          flags: [ required ]
        pdf:
          type: file
          mimeTypes: [ application/pdf ]
          flags: [ useAsPageLink, showInMobileAdmin ]
          filenameField: name

#        description:
#          type: text


# Twig Configuration
twig:
  globals:
    articleAdminPage: '/edit/activity'
    legacyFlags:
      renderPTags
    siteBlocks:
      facebook: Facebook
      albums: Photo Albums Accordion
      calendar: Calendar

swiftmailer:
  disable_delivery: false
#  delivery_addresses: [pelawcbc55@gmail.com]
#  This overrides to address set in code - use at your peril


liip_imagine:

  filter_sets:

#    galleryBigger:
#
#      quality: 70
#
#      filters:
#
#        auto_rotate: ~

    galleryThumb:

      quality: 70

      filters:

        auto_rotate: ~

        scale:

          dim: [ 400,400 ]

