#!/usr/bin/env bash

cd /home/pb.positivemint.com/src/CommonBundle
git reset --hard
git pull

cd /home/pb.positivemint.com
git reset --hard
git pull

php /home/pb.positivemint.com/scripts/cacheBust.php
sh /home/pb.positivemint.com/scripts/cacheClearAndChown