#!/usr/bin/env bash

cd /home/pelawcbc.com/src/CommonBundle
git reset --hard
git pull

cd /home/pelawcbc.com
git reset --hard
git pull

php /home/pelawcbc.com/scripts/cacheBust.php
sh /home/pelawcbc.com/scripts/cacheClearAndChown