#!/usr/bin/expect -f

set timeout -1
set PROMPT "$ "

stty -echo
send_user "Password: "
expect_user -re "(.*)\n" {set PASS $expect_out(1,string)}
stty echo

spawn /usr/bin/ssh -p 25522 positive@212.83.166.128
expect $PROMPT
send -- "sa\r"
expect "git_rsa: "
send -- "$PASS\r"
expect $PROMPT
send -- "pbp\r"
expect "*"
send -- "k\r"
expect $PROMPT
send -- "exit\r"