#!/usr/bin/env bash

cd ~/www/bl_stage
git reset --hard
git pull

cd ~/www/bl_stage/src/CommonBundle
git reset --hard
git pull

cd ~/www/bl_stage/scripts
php ~/www/bl_stage/bin/console cache:clear --env=prod